@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Aug 26 16:54:19 +0200 2026
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_top_level_behav -key {Behavioral:sim_1:Functional:tb_top_level} -tclbatch tb_top_level.tcl -view E:/Formation_FPGA_Expleo/FPGA_Core_Z7/FPGA_Cora_Z7/tp5_crossing_clks_domains/tp5_crossing_clks_domains.sim/tb_top_level_rgb_behav.wcfg -log simulate.log"
call xsim  tb_top_level_behav -key {Behavioral:sim_1:Functional:tb_top_level} -tclbatch tb_top_level.tcl -view E:/Formation_FPGA_Expleo/FPGA_Core_Z7/FPGA_Cora_Z7/tp5_crossing_clks_domains/tp5_crossing_clks_domains.sim/tb_top_level_rgb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
