webtalk_init -webtalk_dir E:/Formation_FPGA_Expleo/FPGA_Core_Z7/FPGA_Cora_Z7/full_adder/full_adder.sim/sim_1/behav/xsim/xsim.dir/testbench_full_adder_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul  3 15:30:37 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c34c9043-0044-421c-89f1-0ac01f3b8a49" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "abec68c75b5649c2b2a75343a879f867" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.30_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8536_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1381665236 -regid "" -xml E:/Formation_FPGA_Expleo/FPGA_Core_Z7/FPGA_Cora_Z7/full_adder/full_adder.sim/sim_1/behav/xsim/xsim.dir/testbench_full_adder_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Formation_FPGA_Expleo/FPGA_Core_Z7/FPGA_Cora_Z7/full_adder/full_adder.sim/sim_1/behav/xsim/xsim.dir/testbench_full_adder_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Formation_FPGA_Expleo/FPGA_Core_Z7/FPGA_Cora_Z7/full_adder/full_adder.sim/sim_1/behav/xsim/xsim.dir/testbench_full_adder_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
