# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Formation_FPGA_Expleo/FPGA_Core_Z7/FPGA_Cora_Z7/tp4_led_driver/tp4_led_driver.srcs/sources_1/ip/fifo/fifo.xci
# IP: The module: 'fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Formation_FPGA_Expleo/FPGA_Core_Z7/FPGA_Cora_Z7/tp4_led_driver/tp4_led_driver.gen/sources_1/ip/fifo/fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Formation_FPGA_Expleo/FPGA_Core_Z7/FPGA_Cora_Z7/tp4_led_driver/tp4_led_driver.gen/sources_1/ip/fifo/fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Formation_FPGA_Expleo/FPGA_Core_Z7/FPGA_Cora_Z7/tp4_led_driver/tp4_led_driver.srcs/sources_1/ip/fifo/fifo.xci
# IP: The module: 'fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Formation_FPGA_Expleo/FPGA_Core_Z7/FPGA_Cora_Z7/tp4_led_driver/tp4_led_driver.gen/sources_1/ip/fifo/fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Formation_FPGA_Expleo/FPGA_Core_Z7/FPGA_Cora_Z7/tp4_led_driver/tp4_led_driver.gen/sources_1/ip/fifo/fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
